/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f71470a2-0291-475a-8c0e-f148a2ab88a9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ODX0gWpK3",
    "aws_user_pools_web_client_id": "7dnuv3biadjlmffj73oskmcdg5",
    "oauth": {
        "domain": "js1342-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
